[package]
name = "L01_stack_heap"
version = "0.1.0"
authors = ["25ma <25mateam@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
